### ISSUE TITLE
Shooter, Conveyor, Intake motors fail to run simultaneously

### ISSUE THREAD

**Issue by dillontherrien** [dillontherrien/7913-FRC-2022#12]

**Comment by BruceMcRooster** [comment]
I created #13 as an idea for using the same code as the Drivetrain for input detection. The one problem may be that the button presses may be missed by the periodic command, since it runs every 20 ms. But if that's alright, conveyor and shooter can be set up in a similar manner, and the conveyor will probably work just fine since its a held button press. 
If shooter is a button hold, then it should work fine too, but it its a toggle it could pose the same issues as the intake in the PR

**Comment by dillontherrien** [comment]
> I created #13 as an idea for using the same code as the Drivetrain for input detection. The one problem may be that the button presses may be missed by the periodic command, since it runs every 20 ms. But if that's alright, conveyor and shooter can be set up in a similar manner, and the conveyor will probably work just fine since its a held button press. If shooter is a button hold, then it should work fine too, but it its a toggle it could pose the same issues as the intake in the PR

20ms is really fast still imo. It is worth a shot!

**Comment by BruceMcRooster** [comment]
Alright, I'm continuing working in a branch of my repo on porting the rest of the things to this same idea, GenericHID.Hand is giving me some grief but it's going alright otherwise. Should have another PR with Conveyor and Shooter in this new style before I leave.
